
- name: shaun192045
  hosts: client_1
  become: true
  become_user: root

  tasks:
  - name: Install nginx
    apt: name=nginx state=present update_cache=true

  - name: Install PostgreSQL
    apt: name=postgresql state=latest update_cache=true
    tags: PostgreSQL

  - name: Create user
    user:
     name: shaun
     password: $6$XzNXDBgpAwy5F$EAs.BGev5oVuDTOjMrbzaQAF28L1hA9WTLjCc6EuXINbugJiYgdTNKwUAKKXSNSVy0bI1CDiWTAxyxPqS6m4I.
     state: present
     shell: /bin/bash

  - name: Creating directory
    file:  
     path: /home/192045
     state: directory

  - name: uninstall nano
    apt: name=nano state=absent
